### ISSUE TITLE
Endpoint for page fault calculation

### ISSUE THREAD

**Issue by masterYoda8** [fabibec/page-replace-visualizer#3]
Create a Backend Endpoint which accepts the following format:
GET faults?frames=9&referenceString=base64(4,5,6,7,8,9)
&FIFO=false&LRU=true&OPT=false&SC=true

The backend function should use the parameters frames and (decoded) referenceString and call the specified function (e.g. LRU and SC because set to true).

The reference string should be used as input in another function which converts the String into an array before it is used in page replacement function.

It should return the aggregated results:
{
	LRU: 79,
	SC: 45,
}

**Comment by fabibec** [comment]
Same as in #8 we need a range of frames that are allowed @masterYoda8 , @masterYoda8

**Comment by masterYoda8** [comment]
I would recommend to allow frames starting with 1 (because 0 would make no sense). The max number has to be tested whether our application is capable of calculation of 50 frames. I think performance wise the length of the reference string has a greater impact then the number of frames. I would suggest to set the limit to 12 for now. When were finished with our application frontend we can trial and error whether a greater number can be handled by our application in a reasonable amount of time. @fabibec
