### ISSUE TITLE
reference string api call does not work on local host

### ISSUE THREAD

**Issue by xgsngxguy** [fabibec/page-replace-visualizer#54]
I always get 307 temporary redirect. After some research i found this articles:
[stackoverflow](https://stackoverflow.com/questions/70351360/keep-getting-307-temporary-redirect-before-returning-status-200-hosted-on-fast)
[github](https://github.com/tiangolo/fastapi/issues/2060#issuecomment-834868906)

The bug is in @app.get("/api/refString/",...): Last slash has to be removed.

**Comment by masterYoda8** [comment]
Merged branch into dev
