### ISSUE TITLE
Function for Second Chance (SC)

### ISSUE THREAD

**Issue by masterYoda8** [fabibec/page-replace-visualizer#6]
This function should accept two inputs (frames: number, referenceString: array).
It should return the number of page faults generated according to SC page replacement algorithm.

**Comment by xgsngxguy** [comment]
@fabibec please revisit your response model structure...I tried to modify my code but I don't get it :(
If your edit is successful, please leave a comment on this issue, so I can create a pull request.
Please use the 6-function-for-second-chance-sc branch for editing, thx.
