### ISSUE TITLE
Endpoint for page fault calculation for range of frames

### ISSUE THREAD

**Issue by masterYoda8** [fabibec/page-replace-visualizer#8]
This Endpoint should accept the following GET request:
GET faultsArray?maxFrames=9&referenceString=base64(4,5,6,7,8,9) &FIFO=false&LRU=true&OPT=false&SC=true

It should calculate the amount of page faults for the specified reference string starting with
x frames up to maxFrames. It returns an Array of page faults for specified page replacement algorithms:

{
	LRU: [89, 78, 5, 6],
	SC: [89, 78, 5, 6],
}

**Comment by fabibec** [comment]
@masterYoda8 , @xgsngxguy  it would be nice if you could provide a range of values that are allowed for the maxFrames Parameter. Moreover, should I add a minFrames  parameter that marks the beginning of the array, or should we start at a fixed number?

**Comment by masterYoda8** [comment]
I think min number would be a great idea. This also means that we have to input fields in our frontend. Min number should be 1 and max number can be set to 12. Keep in mind to check whether user gave min number input which is greater than max number input. For example 7-5 range which should throw an error message. @fabibec

**Comment by xgsngxguy** [comment]
I think it would be nice if I can also start at number 4...and then maybe up to 10. Max value can go up to 20 in my eyes.
In short: Range 1 - 20, but it should be possible to start at a specific number in that range.
